[package]
name = "koumakan"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
serde = "1.0.75"
serde_json = "1.0.26"
serde_derive = "1.0.75"
diesel = { version = "1.3.2", features = ["sqlite", "chrono", "r2d2"] }
chrono = { version = "0.4.6", features = ["serde"] }
md5 = "0.3.8"
rss = "1.5.0"
lettre = "0.8.2"
lettre_email = "0.8.2"
comrak = "0.2.14"
