[package]
name = "koumakan"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "0.16", features = ["sqlite", "chrono"] }
diesel_codegen = { version = "0.16", features = ["sqlite"] }
chrono = { version = "0.4.0", features = ["serde"] }
r2d2 = "0.7"
r2d2-diesel = "0.16"
md5 = "0.3"
