[package]
name = "koumakan"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = { version = "0.3.0", features = ["handlebars_templates"] }
diesel = { version = "0.15.1", features = ["sqlite", "chrono"] }
diesel_codegen = { version = "0.15.0", features = ["sqlite"] }
chrono = "0.4.0"
r2d2 = "0.7.3"
r2d2-diesel = "0.15.0"
