[package]
name = "koumakan"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel_infer_schema = { version = "*", features = ["sqlite"] }
chrono = { version = "*", features = ["serde"] }
r2d2 = "*"
r2d2-diesel = "*"
md5 = "*"
rss = "*"
dotenv = "*"
lettre = "*"
lettre_email = "*"
