[package]
name = "koumakan"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]
edition = "2018"

[dependencies]
common = { path = "../common", features = ["orm"] }

rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["diesel_sqlite_pool"] }
serde = { version = "1.0.102", features = ["derive"] }
chrono = { version = "0.4.9", features = ["serde"] }
md5 = "0.7.0"
rss = "1.8.0"
lettre = { version = "0.9.2", default-features = false, features = ["sendmail-transport"] }
lettre_email = "0.9.2"
comrak = "0.6.2"

diesel = { version = "1.4.3", features = ["sqlite", "chrono", "r2d2"] }
libsqlite3-sys = { version = "0.16.0", features = ["bundled"] }
