[package]
name = "koumakan-backend"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]
edition = "2018"

[dependencies]
common = { path = "../common", features = ["sqlx"] }

dotenv = "0.15.0"
log = "0.4.11"
env_logger = "0.7.1"
bincode = "1.3.1"
serde = { version = "1.0.115", features = ["derive"] }
md5 = "0.7.0"
lettre = "0.10.0-alpha.1"
actix-web = "3.0.0-beta.3"
actix-rt = "1.1.1"
anyhow = "1.0.32"
chrono = "0.4.15"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["macros","migrate","runtime-actix","sqlite"] }
rss = "1.9.0"
