PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE article(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255)  NOT NULL COLLATE NOCASE,
    brief VARCHAR(1024) NOT NULL COLLATE NOCASE,
    content TEXT NOT NULL COLLATE NOCASE,
    category VARCHAR(255) NOT NULL COLLATE NOCASE,
    labels VARCHAR(255) NOT NULL COLLATE NOCASE,
    date DATETIME NOT NULL);
CREATE TABLE comment(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    article_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL COLLATE NOCASE,
    email VARCHAR(255) NOT NULL COLLATE NOCASE,
    website VARCHAR(255) NOT NULL COLLATE NOCASE,
    content VARCHAR(255) NOT NULL COLLATE NOCASE,
    avatar VARCHAR(255) NOT NULL COLLATE NOCASE,
    date DATETIME NOT NULL);
COMMIT;
