[package]
name = "common"
version = "0.1.0"
authors = ["RemiliaForever <remilia@koumakan.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
serde = { version = "1.0.103", features = ["derive"] }
diesel = { version = "1.4.3", features = ["sqlite", "chrono", "r2d2"], optional = true }

[features]
default = []
orm = ["diesel"]
